Pending and done tasks, also generate csv files
Mildred14/todoapp pull request #2
Opened 2018-10-19 00:49 UTC by Mildred14

Description: 
This branch has two different features. 

- First: Pending and done tasks

- Second: Generate csv files

What implements/changes?: 
Added classifications of tasks (pending and done)
An added feature of generating a CSV file
How do you manually test this?: -

Before - After screenshots:
This is how it looks my interface 
![image](https://user-images.githubusercontent.com/26890060/47191745-b5ecd480-d30e-11e8-9b24-898681cdccb1.png)
![image](https://user-images.githubusercontent.com/26890060/47191790-f64c5280-d30e-11e8-80bb-74772d55d794.png)

2018-10-19 03:38 UTC, diegosaul402 requested changes
You're doing it great, but there is a big issue with the lack of relations for your models, you should fix this before continuing.

2018-10-19 03:38 UTC, diegosaul402 commented on db/migrate/20181018233104_add_user_id_to_posts.rb
> +    add_column :posts, :user_id, :integer
The best solution here is explicitly adding the relation here and in your models users and posts.

2018-10-19 03:38 UTC, diegosaul402 commented on app/controllers/posts_controller.rb
> +    @posts_pending_homework =  Post.where(done_homework: false, user_id: current_user.id)
When you make the relations correctly on your migrations and models, all of this kind of code 
will simplify to `@posts_done_homework = Post.where(done_homework: true, user: current_user)` you won't have to explicitly to specify that wich field keeps the relations between your models.

2018-10-19 03:38 UTC, diegosaul402 commented on app/views/posts/index.html.erb
> +<p><%= link_to('Generate Report CSV', posts_path(format: 'csv')) %></p>
Parenthesis for the `link_to` method is unnecessary, rails know that every sentence that follows are arguments.

2018-10-20 00:46 UTC, diegosaul402 requested changes
You still need to do some changes in order to merge.

2018-10-20 00:46 UTC, diegosaul402 commented on db/schema.rb
> +    t.integer "user_id"
your field can't be named `user_id`, just `user`

2018-10-20 00:46 UTC, diegosaul402 commented on app/controllers/posts_controller.rb
> +    @post = Post.new(post_params.merge(user_id: current_user.id))
if your relations are correct, you have to change your names `user_id` for `user` and `current_user.id` for `current_user`, this naming shouln't exist in any part of your code.

2018-10-20 05:33 UTC, kikiondo approved these changes

2018-10-22 20:19 UTC, 8geonirt requested changes
Some small details and suggestions 😅👍

2018-10-22 20:19 UTC, 8geonirt commented on app/controllers/posts_controller.rb
> +    @posts_done_homework = Post.where(done_homework: true, user_id: current_user)
Try to use ActiveRecord relations...
For example, if you have the User model linked to a Post, you can use something like this:
```
has_many :posts
```

And in your Post model
```
belongs_to :user
```

2018-10-22 20:19 UTC, 8geonirt commented on app/controllers/posts_controller.rb
> +    @posts_pending_homework =  Post.where(done_homework: false, user_id: current_user)
Same here...
Oh, what a coincidence... I saw the _done_homework_ variable in another project 😅

2018-10-22 20:19 UTC, 8geonirt commented on app/controllers/posts_controller.rb
> +
Remove this empty space

2018-10-25 23:54 UTC, 8geonirt approved these changes

2018-10-26 00:01 UTC, merged