Feature/add pdf file
Mildred14/todoapp pull request #3
Opened 2018-10-24 05:11 UTC by Mildred14

Description:
I fixed comments done by my **_sensei_** and added pdf file feature!

What implements/changes?:
Scope
Migrations (t.references) 🗺 
Relationship between models(belongs_to, has_many) ❤️ 
Prawn gem💎

2018-10-24 16:38 UTC, 8geonirt submitted a review, later dismissed
Awesome job @Mildred14, I left some small comments that should be addressed, we should keep consistency in code indentation.

2018-10-24 16:38 UTC, 8geonirt commented on app/models/post.rb
> +  belongs_to :user
Add an empty line after this line, this is due to readability reasons, it is easy to read when blocks of methods are separated by empty lines.

2018-10-24 16:38 UTC, 8geonirt commented on app/models/post.rb
> +    def self.to_csv
Fix this indentation 🤓

2018-10-24 16:38 UTC, 8geonirt commented on app/pdfs/posts_pdf.rb
> +        super()
Fix this indentation too

2018-10-24 16:38 UTC, 8geonirt commented on app/views/posts/index.html.erb
> +<h1> Tareas Pendientes</h1>
The space before `Tareas` should be removed

2018-10-25 15:06 UTC, diegosaul402 reviewed
Just one comment

2018-10-25 15:06 UTC, diegosaul402 commented on .vscode/settings.json
> +}
This file is part of your IDE, shouldn't be committed

2018-10-25 20:57 UTC, pacocd commented on app/models/post.rb
> +  end
@8geonirt @diegosaul402 should these methods be declared as scopes? (self.done and self.pending)

2018-10-25 21:01 UTC, pacocd submitted a review, later dismissed

2018-10-25 21:01 UTC, pacocd commented on app/pdfs/posts_pdf.rb
> +end
I see some inconsistencies in code indentation in this file

2018-10-25 21:01 UTC, pacocd commented on app/controllers/posts_controller.rb
> +    @posts_pending_homework =  current_user.posts.pending
@8geonirt @diegosaul402 AFAIK these variables should be part of a separated function, what do you think?

2018-10-25 21:10 UTC, diegosaul402 requested changes
Looks good, only small issues

2018-10-25 21:10 UTC, diegosaul402 commented on app/controllers/posts_controller.rb
> +        filename: "List_#{Date.today}.pdf",
Add indentation to the method arguments please

2018-10-25 21:10 UTC, diegosaul402 commented on app/pdfs/posts_pdf.rb
> +     table line_items_rows
Indentation with two spaces please

2018-10-25 21:10 UTC, diegosaul402 commented on app/pdfs/posts_pdf.rb
> +            [posts.title, posts.body, "#{posts.done_homework}"]
indentation with two spaces

2018-10-25 21:48 UTC, diegosaul402 approved these changes
Great work! LGTM :shipit:

2018-10-25 23:14 UTC, archisss reviewed
you can merge

2018-10-25 23:14 UTC, archisss commented on app/controllers/posts_controller.rb
> +        filename: "List_#{Date.today}.pdf",
iddentation for a better and readable code

2018-10-25 23:14 UTC, archisss commented on app/pdfs/posts_pdf.rb
> +end
this file should be indented the right way

2018-10-25 23:14 UTC, archisss approved these changes

2018-10-25 23:19 UTC, edumartinez16 commented
Great work!

2018-10-25 23:20 UTC, kikiondo approved these changes

2018-10-25 23:28 UTC, edumartinez16 approved these changes

2018-10-26 00:01 UTC, merged